package rules

import (
	"fmt"
	"sort"
	"strings"

	v1alpha1 "github.com/agarwalvivek29/kubedrill/apis/challenge/v1alpha1"
)

// AuditLogPath is where the apiserver writes the audit log on the control-plane
// node (see the generated policy's mount). AuditEvents streams from here.
const AuditLogPath = "/var/log/kubernetes/audit/audit.log"

// AuditPolicy generates the API-server audit policy for a challenge (AD-5,
// FR-12). It returns "" when the challenge has no rules — an unruled challenge
// needs no audit and pays no logging cost.
//
// The policy is two-tier, and the rule ORDER matters (first match wins):
//  1. Secrets are pinned to Metadata ALWAYS — their contents are never captured,
//     even if some other rule would ask for more. This is first so it wins.
//  2. Request level (captures the request body) for exactly the kinds named by a
//     field-level `require` rule — that is the only place grading needs to see
//     what was submitted.
//  3. A Metadata baseline for all mutating verbs cluster-wide — enough to grade
//     deny/protect/require by (verb, object, actor) without logging bodies.
//
// Reads are never logged (no rule matches get/list/watch), keeping the log small
// and focused on what changes state.
func AuditPolicy(ch *v1alpha1.Challenge) string {
	if len(ch.Rules) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("apiVersion: audit.k8s.io/v1\n")
	b.WriteString("kind: Policy\n")
	b.WriteString("# Generated by kubedrill from the challenge's rules. Do not edit.\n")
	b.WriteString("omitStages:\n  - RequestReceived\n")
	b.WriteString("rules:\n")

	// 1. Secrets: Metadata always (never capture secret contents).
	b.WriteString("  # Secrets are always Metadata-only — contents are never captured.\n")
	b.WriteString("  - level: Metadata\n")
	b.WriteString("    resources:\n")
	b.WriteString("      - group: \"\"\n")
	b.WriteString("        resources: [\"secrets\"]\n")

	// 2. Request level for kinds referenced by a field-level require rule.
	if gr := fieldRequireResources(ch); len(gr) > 0 {
		b.WriteString("  # Request level for kinds a field-level `require` inspects.\n")
		b.WriteString("  - level: Request\n")
		b.WriteString("    verbs: [\"create\", \"update\", \"patch\"]\n")
		b.WriteString("    resources:\n")
		for _, r := range gr {
			fmt.Fprintf(&b, "      - group: %q\n        resources: [%q]\n", r.group, r.resource)
		}
	}

	// 3. Metadata baseline for all mutating verbs.
	b.WriteString("  # Baseline: every mutating action, at Metadata level.\n")
	b.WriteString("  - level: Metadata\n")
	b.WriteString("    verbs: [\"create\", \"update\", \"patch\", \"delete\", \"deletecollection\"]\n")

	return b.String()
}

type groupResource struct{ group, resource string }

// fieldRequireResources collects the (group, resource) of every kind named by a
// field-level require rule, deduplicated and sorted for a stable policy. Secrets
// are excluded — a field-level require on a Secret is a lint error (Story 2.3),
// and they are pinned to Metadata regardless.
func fieldRequireResources(ch *v1alpha1.Challenge) []groupResource {
	seen := map[groupResource]bool{}
	for _, r := range ch.Rules {
		if r.Require == nil || len(r.Require.Fields) == 0 {
			continue
		}
		kind := r.Require.Match.Kind
		if strings.EqualFold(kind, "Secret") {
			continue
		}
		gr := kindToResource(kind)
		if gr.resource == "secrets" {
			continue
		}
		seen[gr] = true
	}
	out := make([]groupResource, 0, len(seen))
	for gr := range seen {
		out = append(out, gr)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].group != out[j].group {
			return out[i].group < out[j].group
		}
		return out[i].resource < out[j].resource
	})
	return out
}

// kindToResource maps a Kubernetes Kind to its (group, resource) for an audit
// policy. Covers the core/apps/networking/rbac kinds a challenge realistically
// field-requires; unknown kinds fall back to a lowercased, naively-pluralized
// resource in the core group (an over- or under-match only affects Request-level
// body capture, never Metadata grading).
func kindToResource(kind string) groupResource {
	switch kind {
	case "ConfigMap":
		return groupResource{"", "configmaps"}
	case "Service":
		return groupResource{"", "services"}
	case "ServiceAccount":
		return groupResource{"", "serviceaccounts"}
	case "PersistentVolumeClaim":
		return groupResource{"", "persistentvolumeclaims"}
	case "Pod":
		return groupResource{"", "pods"}
	case "Deployment":
		return groupResource{"apps", "deployments"}
	case "StatefulSet":
		return groupResource{"apps", "statefulsets"}
	case "DaemonSet":
		return groupResource{"apps", "daemonsets"}
	case "ReplicaSet":
		return groupResource{"apps", "replicasets"}
	case "Ingress":
		return groupResource{"networking.k8s.io", "ingresses"}
	case "NetworkPolicy":
		return groupResource{"networking.k8s.io", "networkpolicies"}
	case "Role", "ClusterRole":
		return groupResource{"rbac.authorization.k8s.io", strings.ToLower(kind) + "s"}
	case "RoleBinding", "ClusterRoleBinding":
		return groupResource{"rbac.authorization.k8s.io", strings.ToLower(kind) + "s"}
	case "Job":
		return groupResource{"batch", "jobs"}
	case "CronJob":
		return groupResource{"batch", "cronjobs"}
	default:
		return groupResource{"", strings.ToLower(kind) + "s"}
	}
}
