apiVersion: v1
kind: Namespace
metadata:
  name: retail
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshop
  namespace: retail
spec:
  replicas: 3
  selector:
    matchLabels: { app: webshop }
  template:
    metadata:
      labels: { app: webshop }
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests: { cpu: 10m, memory: 16Mi }
            limits: { memory: 64Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: webshop
  namespace: retail
spec:
  selector: { app: webshop }
  ports:
    - port: 80
      targetPort: 80
